[2024-05-03T11:09:44.701+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:09:44.720+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_to_postgres.create_table manual__2024-05-03T11:04:38.974879+00:00 [queued]>
[2024-05-03T11:09:44.729+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_to_postgres.create_table manual__2024-05-03T11:04:38.974879+00:00 [queued]>
[2024-05-03T11:09:44.729+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-03T11:09:44.743+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_table> on 2024-05-03 11:04:38.974879+00:00
[2024-05-03T11:09:44.749+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-03T11:09:44.750+0000] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2024-05-03T11:09:44.751+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_data_to_postgres', 'create_table', 'manual__2024-05-03T11:04:38.974879+00:00', '--job-id', '809', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmpopq7jvmo']
[2024-05-03T11:09:44.754+0000] {standard_task_runner.py:91} INFO - Job 809: Subtask create_table
[2024-05-03T11:09:44.794+0000] {task_command.py:426} INFO - Running <TaskInstance: load_data_to_postgres.create_table manual__2024-05-03T11:04:38.974879+00:00 [running]> on host 16eb94e6c712
[2024-05-03T11:09:44.868+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='air' AIRFLOW_CTX_DAG_ID='load_data_to_postgres' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T11:04:38.974879+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T11:04:38.974879+00:00'
[2024-05-03T11:09:44.870+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:09:44.881+0000] {sql.py:276} INFO - Executing: 
CREATE TABLE IF NOT EXISTS vehicles (
    id SERIAL PRIMARY KEY,
    track_id INT NOT NULL,
    vehicle_type VARCHAR(500) NOT NULL,
    traveled_d VARCHAR(500) NOT NULL,
    avg_speed FLOAT NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    speed FLOAT NOT NULL,
    lon_acc FLOAT NOT NULL,
    lat_acc FLOAT NOT NULL,
    time FLOAT NOT NULL
)
[2024-05-03T11:09:44.890+0000] {base.py:84} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-05-03T11:09:44.899+0000] {base.py:84} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-05-03T11:09:44.900+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:09:44.901+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-05-03T11:09:44.911+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=load_data_to_postgres, task_id=create_table, execution_date=20240503T110438, start_date=20240503T110944, end_date=20240503T110944
[2024-05-03T11:09:44.924+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 809 for task create_table (connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 122)
[2024-05-03T11:09:44.931+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T11:09:44.940+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-03T11:09:44.951+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:09:44.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
