[2024-05-01T15:56:45.430+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/load.py
[2024-05-01T15:56:45.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T15:56:45.438+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:56:45.437+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T15:56:46.884+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:56:46.875+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T15:56:46.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T15:56:46.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.502 seconds
[2024-05-01T15:57:27.736+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/load.py
[2024-05-01T15:57:27.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T15:57:27.746+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:57:27.745+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T15:57:29.764+0000] {logging_mixin.py:188} INFO - [2024-05-01T15:57:29.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T15:57:29.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T15:57:29.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 2.102 seconds
[2024-05-01T16:03:35.912+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/load.py
[2024-05-01T16:03:35.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:03:35.927+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:03:35.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:03:37.246+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:03:37.234+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:03:37.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:03:37.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.410 seconds
[2024-05-01T16:04:15.234+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/load.py
[2024-05-01T16:04:15.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:04:15.252+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:04:15.251+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:04:16.328+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:04:16.322+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:04:16.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:04:16.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.143 seconds
[2024-05-01T16:06:11.877+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/load.py
[2024-05-01T16:06:11.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:06:11.901+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:06:11.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:06:13.024+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:06:13.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:06:13.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:06:13.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.225 seconds
[2024-05-01T16:06:59.920+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/load.py
[2024-05-01T16:06:59.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:06:59.937+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:06:59.936+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:07:01.255+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:07:01.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:07:01.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:07:01.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.389 seconds
[2024-05-01T16:08:45.149+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/load.py
[2024-05-01T16:08:45.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:08:45.166+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:08:45.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:08:45.973+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:08:45.963+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:08:45.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:08:46.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.869 seconds
[2024-05-01T16:09:16.842+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/load.py
[2024-05-01T16:09:16.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:09:16.847+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:09:16.847+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:09:17.342+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:09:17.338+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:09:17.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:09:17.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.528 seconds
[2024-05-01T16:16:12.383+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/load.py
[2024-05-01T16:16:12.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:16:12.403+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:16:12.402+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:16:13.416+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:16:13.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:16:13.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:16:13.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.078 seconds
[2024-05-01T16:16:44.053+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/load.py
[2024-05-01T16:16:44.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:16:44.057+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:16:44.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:16:44.502+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:16:44.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:16:44.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:16:44.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.488 seconds
[2024-05-01T16:17:14.673+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/load.py
[2024-05-01T16:17:14.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:17:14.676+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:17:14.676+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:17:15.058+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:17:15.055+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:17:15.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:17:15.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.411 seconds
[2024-05-01T16:17:45.170+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/load.py
[2024-05-01T16:17:45.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:17:45.173+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:17:45.173+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:17:45.547+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:17:45.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:17:45.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:17:45.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.400 seconds
[2024-05-01T16:18:16.009+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/load.py
[2024-05-01T16:18:16.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:18:16.015+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:18:16.014+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:18:16.462+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:18:16.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:18:16.468+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:18:16.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.484 seconds
[2024-05-01T16:18:46.627+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/load.py
[2024-05-01T16:18:46.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:18:46.632+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:18:46.631+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:18:47.107+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:18:47.104+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:18:47.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:18:47.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.506 seconds
[2024-05-01T16:19:17.228+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/load.py
[2024-05-01T16:19:17.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:19:17.232+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:19:17.231+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:19:17.708+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:19:17.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:19:17.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:19:17.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.506 seconds
[2024-05-01T16:19:47.940+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/load.py
[2024-05-01T16:19:47.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:19:47.944+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:19:47.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:19:48.433+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:19:48.429+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:19:48.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:19:48.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.521 seconds
[2024-05-01T16:20:18.494+0000] {processor.py:161} INFO - Started process (PID=523) to work on /opt/airflow/dags/load.py
[2024-05-01T16:20:18.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:20:18.500+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:20:18.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:20:18.927+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:20:18.923+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:20:18.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:20:18.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.457 seconds
[2024-05-01T16:20:49.201+0000] {processor.py:161} INFO - Started process (PID=585) to work on /opt/airflow/dags/load.py
[2024-05-01T16:20:49.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:20:49.207+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:20:49.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:20:50.144+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:20:50.139+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:20:50.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:20:50.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.970 seconds
[2024-05-01T16:39:21.559+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/load.py
[2024-05-01T16:39:21.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:39:21.577+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:39:21.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:39:22.512+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:39:22.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:39:22.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:39:22.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 1.010 seconds
[2024-05-01T16:39:53.057+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/load.py
[2024-05-01T16:39:53.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:39:53.062+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:39:53.062+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:39:53.538+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:39:53.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:39:53.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:39:53.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.515 seconds
[2024-05-01T16:40:23.753+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/load.py
[2024-05-01T16:40:23.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:40:23.758+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:40:23.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:40:24.287+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:40:24.283+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:40:24.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:40:24.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.566 seconds
[2024-05-01T16:40:54.918+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/load.py
[2024-05-01T16:40:54.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:40:54.923+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:40:54.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:40:55.343+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:40:55.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:40:55.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:40:55.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.450 seconds
[2024-05-01T16:41:25.576+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/load.py
[2024-05-01T16:41:25.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:41:25.581+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:41:25.581+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:41:26.404+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:41:26.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:41:26.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:41:26.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.873 seconds
[2024-05-01T16:41:57.051+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/load.py
[2024-05-01T16:41:57.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load.py for tasks to queue
[2024-05-01T16:41:57.057+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:41:57.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load.py
[2024-05-01T16:41:57.678+0000] {logging_mixin.py:188} INFO - [2024-05-01T16:41:57.667+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load.py", line 66, in <module>
    create_table >> load_data
                    ^^^^^^^^^
NameError: name 'load_data' is not defined
[2024-05-01T16:41:57.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load.py
[2024-05-01T16:41:57.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load.py took 0.673 seconds
